function receiveMessageString(n){"use strict";var t={};t.data=n;t.source="";receiveMessage(t)}function receiveMessage(n){"use strict";var r,s,a,h,f,c,v,y,p,w,l;if(localCompartment===null&&(localCompartment=n.source),MSG_TYPE_ADPARAMS===n.data.substr(0,MSG_TYPE_ADPARAMS.length)){if(r=n.data.substr(MSG_TYPE_ADPARAMS.length+1),r!=="")try{adParams=JSON.parse(r)}catch(e){reportAdError("Ad params JSON parse error: "+e.message)}}else if(MSG_TYPE_PRMPARAMS===n.data.substr(0,MSG_TYPE_PRMPARAMS.length)){if(r=n.data.substr(MSG_TYPE_PRMPARAMS.length+1),r!=="")try{prmParams=JSON.parse(r)}catch(e){reportAdError("Prm params JSON parse error: "+e.message)}}else if(MSG_TYPE_APPPARAMS===n.data.substr(0,MSG_TYPE_APPPARAMS.length)){if(r=n.data.substr(MSG_TYPE_APPPARAMS.length+1),r!=="")try{appParams=JSON.parse(r)}catch(e){reportAdError("App options JSON parse error: "+e.message)}}else if(MSG_TYPE_SETID===n.data.substr(0,MSG_TYPE_SETID.length))adControlId=n.data.substr(MSG_TYPE_SETID.length+1);else if(MSG_TYPE_INIT!==n.data.substr(0,MSG_TYPE_INIT.length)&&typeof Ormma!="undefined"&&Ormma!==null){var u=n.data,t=null,i=null,o=u.indexOf(":");o<0?t=u:(t=u.substr(0,o),i=u.substr(o+1));t===MSG_TYPE_SETSIZE?(s=JSON.parse(i),Ormma._setSize(s.width,s.height)):t===MSG_TYPE_SETMAXSIZE?(a=JSON.parse(i),Ormma._maxSize=a):t===MSG_TYPE_SETSCREENSIZE?(h=JSON.parse(i),Ormma._setScreenSize(h.width,h.height)):t===MSG_TYPE_SETSTATE?Ormma._setState(i):t===MSG_TYPE_SETLOCALE?Ormma._setLocale(i):t===MSG_TYPE_SETSDKINFO?(f=JSON.parse(i),Ormma._setSdkVersion(f.sdkVersion,f.client,f.runtimeType)):t===MSG_TYPE_SETCAPABILITY?(c=JSON.parse(i),Ormma._setCapability(c.capability,c.value)):t===MSG_TYPE_SETPLACEMENTTYPE?Ormma._setPlacementType(i):t===MSG_TYPE_START?Ormma._init(i):t===MSG_TYPE_FIRESHAKE?Ormma._shake():t===MSG_TYPE_ORMMA_RESPONSE?Ormma._sendResponse(JSON.parse(i)):t===MSG_TYPE_UPDATETILTCOORDS?(v=JSON.parse(i),Ormma._tiltChange(v)):t===MSG_TYPE_VIEWABLECHANGE?(y=JSON.parse(i),Ormma._viewableChange(y.viewable)):t===MSG_TYPE_UPDATEORIENTATION?(p=JSON.parse(i),Ormma._setOrientation(p.orientation)):t===MSG_TYPE_SETNETWORK?Ormma._setNetwork(i):t===MSG_TYPE_WIREAPPEVENTS?(w=JSON.parse(i),_wireApplicationEvents(w)):t===MSG_TYPE_ERROR?(l=JSON.parse(i),Ormma._throwError(l.action,l.message)):t===MSG_TYPE_SETFOCUS&&i==="true"&&document.body.focus()}}function reportAdError(n){"use strict";console.log(n);postToLocal(MSG_TYPE_ERROR+":"+n)}function postToLocal(n){"use strict";localCompartment!=null&&window.external.notify(n)}function _wireApplicationEvents(n){"use strict";if(n!==null&&typeof n!="undefined"){var t=parseInt(n.events);(t&EVENT_TYPE_ENUM.PointerDown)!=0&&typeof applicationEventHandlers.onPointerDown!="function"?(applicationEventHandlers.onPointerDown=function(t){t.which===2&&n.preventDefault&&t.preventDefault();pointerDown=!0;postToLocal(MSG_TYPE_ONPOINTERDOWN+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,pointerType:t.pointerType,which:t.which}))},window.addEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1)):(t&EVENT_TYPE_ENUM.PointerDown)==0&&typeof applicationEventHandlers.onPointerDown=="function"&&(window.removeEventListener("MSPointerDown",applicationEventHandlers.onPointerDown,!1),applicationEventHandlers.onPointerDown=null);(t&EVENT_TYPE_ENUM.PointerUp)!=0&&typeof applicationEventHandlers.onPointerUp!="function"?(applicationEventHandlers.onPointerUp=function(n){n.type==="pointerout"?pointerDown&&(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP)):(pointerDown=!1,postToLocal(MSG_TYPE_ONPOINTERUP))},window.addEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.addEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1)):(t&EVENT_TYPE_ENUM.PointerUp)==0&&typeof applicationEventHandlers.onPointerUp=="function"&&(window.removeEventListener("MSPointerUp",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerCancel",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSPointerOut",applicationEventHandlers.onPointerUp,!1),window.removeEventListener("MSLostPointerCapture",applicationEventHandlers.onPointerUp,!1),applicationEventHandlers.onPointerUp=null);(t&EVENT_TYPE_ENUM.PointerMove)!=0&&typeof applicationEventHandlers.onPointerMove!="function"?(applicationEventHandlers.onPointerMove=function(n){postToLocal(MSG_TYPE_ONPOINTERMOVE+":"+JSON.stringify({clientX:n.clientX,clientY:n.clientY}))},window.addEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1)):(t&EVENT_TYPE_ENUM.PointerMove)==0&&typeof applicationEventHandlers.onPointerMove=="function"&&(window.removeEventListener("MSPointerMove",applicationEventHandlers.onPointerMove,!1),applicationEventHandlers.onPointerMove=null);(t&EVENT_TYPE_ENUM.ManipulationStateChanged)!=0&&typeof applicationEventHandlers.onManipulationStateChanged!="function"?(applicationEventHandlers.onManipulationStateChanged=function(n){postToLocal(MSG_TYPE_ONMANIPSTATECHANGED+":"+JSON.stringify({lastState:n.lastState,currentState:n.currentState}))},window.addEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1)):(t&EVENT_TYPE_ENUM.ManipulationStateChanged)==0&&typeof applicationEventHandlers.onManipulationStateChanged=="function"&&(window.removeEventListener("MSManipulationStateChanged",applicationEventHandlers.onManipulationStateChanged,!1),applicationEventHandlers.onManipulationStateChanged=null);(t&EVENT_TYPE_ENUM.MouseWheel)!=0&&typeof applicationEventHandlers.onMouseWheel!="function"?(applicationEventHandlers.onMouseWheel=function(t){n.preventDefault&&t.preventDefault();postToLocal(MSG_TYPE_ONMOUSEWHEEL+":"+JSON.stringify({clientX:t.clientX,clientY:t.clientY,ctrlKey:t.ctrlKey,wheelDelta:t.wheelDelta}))},window.addEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1)):(t&EVENT_TYPE_ENUM.MouseWheel)==0&&typeof applicationEventHandlers.onMouseWheel=="function"&&(window.removeEventListener("mousewheel",applicationEventHandlers.onMouseWheel,!1),applicationEventHandlers.onMouseWheel=null)}}window.onerror=function(n,t,i){"use strict";try{console.error("[msg:"+n+"][url:"+t+"][lineNumber:"+i+"]");window.external.notify("error:unhandled ad exception: "+n)}catch(r){}return!0};var localCompartment=null,adControlId=null,pointerDown,adParams=null,prmParams=null,appParams=null,MSG_TYPE_ADPARAMS="adParams",MSG_TYPE_PRMPARAMS="prmParams",MSG_TYPE_APPPARAMS="appParams",MSG_TYPE_INIT="init",MSG_TYPE_SETID="setId",MSG_TYPE_ERROR="error",MSG_TYPE_SETMAXSIZE="setMaxSize",MSG_TYPE_SETSCREENSIZE="setScreenSize",MSG_TYPE_SETSIZE="setSize",MSG_TYPE_SETSTATE="setState",MSG_TYPE_SETPLACEMENTTYPE="setPlacementType",MSG_TYPE_WIREAPPEVENTS="wireAppEvents",MSG_TYPE_START="ormmaStart",MSG_TYPE_ORMMA_RESPONSE="ormmaResponse",MSG_TYPE_FIRESHAKE="fireShake",MSG_TYPE_UPDATETILTCOORDS="updateTiltCoords",MSG_TYPE_UPDATEORIENTATION="updateOrienation",MSG_TYPE_VIEWABLECHANGE="viewableChange",MSG_TYPE_SETNETWORK="setNetwork",MSG_TYPE_SETLOCALE="setLocale",MSG_TYPE_SETSDKINFO="setSdkInfo",MSG_TYPE_SETCAPABILITY="setCapability",MSG_TYPE_SETFOCUS="setFocus",MSG_TYPE_ONPOINTERDOWN="MSPointerDown",MSG_TYPE_ONPOINTERUP="MSPointerUp",MSG_TYPE_ONPOINTERMOVE="MSPointerMove",MSG_TYPE_ONMOUSEWHEEL="MSMouseWheel",MSG_TYPE_ONMANIPSTATECHANGED="MSManipulationStateChanged",EVENT_TYPE_ENUM={All:-1,PointerDown:1,PointerUp:2,PointerMove:4,MouseWheel:16,ManipulationStateChanged:32},applicationEventHandlers={onPointerDown:null,onPointerUp:null,onMouseWheel:null,onPointerMove:null,onManipulationStateChanged:null};
// SIG // Begin signature block
// SIG // MIIdogYJKoZIhvcNAQcCoIIdkzCCHY8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFKpjhl5i8bQd
// SIG // HBrsOnhMdcMSqlmFoIIYZDCCBMMwggOroAMCAQICEzMA
// SIG // AACsYxbn40ZVsxwAAAAAAKwwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDUwMzE3
// SIG // MTMyM1oXDTE3MDgwMzE3MTMyM1owgbMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsT
// SIG // Hm5DaXBoZXIgRFNFIEVTTjpDMEY0LTMwODYtREVGODEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBAJ8h3YTccknLV/hvi0hiAhANf1YT1ZtfcdeBRgUA
// SIG // lKkNQEzmvMz9WRplOiTlI/ECx5uEgMJSr6LBi/KNN1XK
// SIG // QjbDftNeYzF24YT+8DE2aQA05eRMPO+nUqoCkcRLbmh4
// SIG // +LCbt1tX4SfWKpsHqflc+fo3FEFdiGSwcONZpljGhi2o
// SIG // aWi27pflzme8Itvqn06z1WKQd74VTMGqSxJDN9obDlH5
// SIG // fqGb7gH0cDwRcWPxptJ2XE2wddo0q/EKwRe8n9Xv9yko
// SIG // qpXnItxm0mU/PeiznK+235uZzV/HxFqMOlmVgayOiyj8
// SIG // fbd3HsuLc9KQHXV9jeiwErd0NB4Ozf87IDmL65cCAwEA
// SIG // AaOCAQkwggEFMB0GA1UdDgQWBBQhVywB7YNQaGndwU1p
// SIG // q42rT5Q3YjAfBgNVHSMEGDAWgBQjNPjZUkZwCu1A+3b7
// SIG // syuwwzWzDzBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
// SIG // Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
// SIG // cy9NaWNyb3NvZnRUaW1lU3RhbXBQQ0EuY3JsMFgGCCsG
// SIG // AQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL3d3
// SIG // dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3Nv
// SIG // ZnRUaW1lU3RhbXBQQ0EuY3J0MBMGA1UdJQQMMAoGCCsG
// SIG // AQUFBwMIMA0GCSqGSIb3DQEBBQUAA4IBAQBGNopaApng
// SIG // TXZuCD1daUIu3+BLDZqLVDHp+Q/A4OKzixPSZHdJTTi+
// SIG // XIZlivnfQSxuUqrD9Ef4KqYeIRxWTOC1R1K0sUHEC1gR
// SIG // In6zNgXjdBumKUYhge550KqvOvjcF/daS4SeSwcyaPhL
// SIG // nFhShZhAVyzAS/OX8grrApNEaMHR6aoebN84ZDIIxV/n
// SIG // F1syV1C3xnxD7wlwyiIMbHOZFGpWInv5pAim6VlxFuoD
// SIG // fhTTyk274x3AsbXH/ZlXqpQOY6ExXviWzMoLTk3l9DJX
// SIG // +K07wq395ANM7ESS/8uSXYoXcUj/Jyl+R9ENglpgw2Ps
// SIG // b28fbS3qrP2xE6WjM+yv/wH+MIIGBzCCA++gAwIBAgIK
// SIG // YRZoNAAAAAAAHDANBgkqhkiG9w0BAQUFADBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDcwNDAz
// SIG // MTI1MzA5WhcNMjEwNDAzMTMwMzA5WjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
// SIG // DwAwggEKAoIBAQCfoWyx39tIkip8ay4Z4b3i48WZUSNQ
// SIG // rc7dGE4kD+7Rp9FMrXQwIBHrB9VUlRVJlBtCkq6YXDAm
// SIG // 2gBr6Hu97IkHD/cOBJjwicwfyzMkh53y9GccLPx754gd
// SIG // 6udOo6HBI1PKjfpFzwnQXq/QsEIEovmmbJNn1yjcRlOw
// SIG // htDlKEYuJ6yGT1VSDOQDLPtqkJAwbofzWTCd+n7Wl7Po
// SIG // IZd++NIT8wi3U21StEWQn0gASkdmEScpZqiX5NMGgUqi
// SIG // +YSnEUcUCYKfhO1VeP4Bmh1QCIUAEDBG7bfeI0a7xC1U
// SIG // n68eeEExd8yb3zuDk6FhArUdDbH895uyAc4iS1T/+QXD
// SIG // wiALAgMBAAGjggGrMIIBpzAPBgNVHRMBAf8EBTADAQH/
// SIG // MB0GA1UdDgQWBBQjNPjZUkZwCu1A+3b7syuwwzWzDzAL
// SIG // BgNVHQ8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwgZgG
// SIG // A1UdIwSBkDCBjYAUDqyCYEBWJ5flJRP8KuEKU5VZ5KSh
// SIG // Y6RhMF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJ
// SIG // kiaJk/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eYIQea0WoUqgpa1Mc1j0BxMuZTBQBgNVHR8ESTBHMEWg
// SIG // Q6BBhj9odHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtp
// SIG // L2NybC9wcm9kdWN0cy9taWNyb3NvZnRyb290Y2VydC5j
// SIG // cmwwVAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjho
// SIG // dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRz
// SIG // L01pY3Jvc29mdFJvb3RDZXJ0LmNydDATBgNVHSUEDDAK
// SIG // BggrBgEFBQcDCDANBgkqhkiG9w0BAQUFAAOCAgEAEJeK
// SIG // w1wDRDbd6bStd9vOeVFNAbEudHFbbQwTq86+e4+4LtQS
// SIG // ooxtYrhXAstOIBNQmd16QOJXu69YmhzhHQGGrLt48ovQ
// SIG // 7DsB7uK+jwoFyI1I4vBTFd1Pq5Lk541q1YDB5pTyBi+F
// SIG // A+mRKiQicPv2/OR4mS4N9wficLwYTp2OawpylbihOZxn
// SIG // LcVRDupiXD8WmIsgP+IHGjL5zDFKdjE9K3ILyOpwPf+F
// SIG // ChPfwgphjvDXuBfrTot/xTUrXqO/67x9C0J71FNyIe4w
// SIG // yrt4ZVxbARcKFA7S2hSY9Ty5ZlizLS/n+YWGzFFW6J1w
// SIG // lGysOUzU9nm/qhh6YinvopspNAZ3GmLJPR5tH4LwC8cs
// SIG // u89Ds+X57H2146SodDW4TsVxIxImdgs8UoxxWkZDFLyz
// SIG // s7BNZ8ifQv+AeSGAnhUwZuhCEl4ayJ4iIdBD6Svpu/RI
// SIG // zCzU2DKATCYqSCRfWupW76bemZ3KOm+9gSd0BhHudiG/
// SIG // m4LBJ1S2sWo9iaF2YbRuoROmv6pH8BJv/YoybLL+31HI
// SIG // jCPJZr2dHYcSZAI9La9Zj7jkIeW1sMpjtHhUBdRBLlCs
// SIG // lLCleKuzoJZ1GtmShxN1Ii8yqAhuoFuMJb+g74TKIdbr
// SIG // Hk/Jmu5J4PcBZW+JC33Iacjmbuqnl84xKf8OxVtc2E0b
// SIG // odj6L54/LlUWa8kTo/0wggYQMIID+KADAgECAhMzAAAA
// SIG // ZEeElIbbQRk4AAAAAABkMA0GCSqGSIb3DQEBCwUAMH4x
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
// SIG // c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcNMTUx
// SIG // MDI4MjAzMTQ2WhcNMTcwMTI4MjAzMTQ2WjCBgzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjENMAsGA1UECxMETU9QUjEeMBwG
// SIG // A1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMIIBIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAky7a2OY+
// SIG // mNkbD2RfTahYTRQ793qE/DwRMTrvicJKLUGlSF3dEp7v
// SIG // q2YoNNV9KlV7TE2K8sDxstNSFYu2swi4i1AL3X/7agmg
// SIG // 3GcExPHfvHUYIEC+eCyZVt3u9S7dPkL5Wh8wrgEUirCC
// SIG // tVGg4m1l/vcYCo0wbU06p8XzNi3uXyygkgCxHEziy/f/
// SIG // JCV/14/A3ZduzrIXtsccRKckyn6B5uYxuRbZXT7RaO6+
// SIG // zUjQhiyu3A4hwcCKw+4bk1kT9sY7gHIYiFP7q78wPqB3
// SIG // vVKIv3rY6LCTraEbjNR+phBQEL7hyBxk+ocu+8RHZhbA
// SIG // hHs2r1+6hURsAg8t4LAOG6I+JQIDAQABo4IBfzCCAXsw
// SIG // HwYDVR0lBBgwFgYIKwYBBQUHAwMGCisGAQQBgjdMCAEw
// SIG // HQYDVR0OBBYEFFhWcQTwvbsz9YNozOeARvdXr9IiMFEG
// SIG // A1UdEQRKMEikRjBEMQ0wCwYDVQQLEwRNT1BSMTMwMQYD
// SIG // VQQFEyozMTY0Mis0OWU4YzNmMy0yMzU5LTQ3ZjYtYTNi
// SIG // ZS02YzhjNDc1MWM0YjYwHwYDVR0jBBgwFoAUSG5k5VAF
// SIG // 04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZD
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // cmwvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // bDBhBggrBgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
// SIG // dHMvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IC
// SIG // AQCI4gxkQx3dXK6MO4UktZ1A1r1mrFtXNdn06DrARZkQ
// SIG // Tdu0kOTLdlGBCfCzk0309RLkvUgnFKpvLddrg9TGp3n8
// SIG // 0yUbRsp2AogyrlBU+gP5ggHFi7NjGEpj5bH+FDsMw9Py
// SIG // gLg8JelgsvBVudw1SgUt625nY7w1vrwk+cDd58TvAyJQ
// SIG // FAW1zJ+0ySgB9lu2vwg0NKetOyL7dxe3KoRLaztUcqXo
// SIG // YW5CkI+Mv3m8HOeqlhyfFTYxPB5YXyQJPKQJYh8zC9b9
// SIG // 0JXLT7raM7mQ94ygDuFmlaiZ+QSUR3XVupdEngrmZgUB
// SIG // 5jX13M+Pl2Vv7PPFU3xlo3Uhj1wtupNC81epoxGhJ0tR
// SIG // uLdEajD/dCZ0xIniesRXCKSC4HCL3BMnSwVXtIoj/QFy
// SIG // mFYwD5+sAZuvRSgkKyD1rDA7MPcEI2i/Bh5OMAo9App4
// SIG // sR0Gp049oSkXNhvRi/au7QG6NJBTSBbNBGJG8Qp+5QTh
// SIG // KoQUk8mj0ugr4yWRsA9JTbmqVw7u9suB5OKYBMUN4hL/
// SIG // yI+aFVsE/KJInvnxSzXJ1YHka45ADYMKAMl+fLdIqm3n
// SIG // x6rIN0RkoDAbvTAAXGehUCsIod049A1T3IJyUJXt3OsT
// SIG // d3WabhIBXICYfxMg10naaWcyUePgW3+VwP0XLKu4O1+8
// SIG // ZeGyaDSi33GnzmmyYacX3BTqMDCCB3owggVioAMCAQIC
// SIG // CmEOkNIAAAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29m
// SIG // dCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEx
// SIG // MB4XDTExMDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVow
// SIG // fjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWlj
// SIG // cm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIw
// SIG // DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQ
// SIG // HC6t2G6qghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/D
// SIG // DB7dN2vGEtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRs
// SIG // r55JnOloXtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ2
// SIG // 6DJSJhIv56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea6
// SIG // 4DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3
// SIG // vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuG
// SIG // G9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGy
// SIG // r5I4ftKdgCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOG
// SIG // jfdf8NBSv4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKu
// SIG // HCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0Xpb
// SIG // L9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/p
// SIG // I0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkw
// SIG // p6uO3+xbn6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4Dm
// SIG // imJ4X7IvhNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJ
// SIG // TMXUpUMvdJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSW
// SIG // sLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEE
// SIG // AYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQw
// SIG // WgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEF
// SIG // BQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2Vy
// SIG // QXV0MjAxMV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGX
// SIG // MIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEW
// SIG // M2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
// SIG // ZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0
// SIG // HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMA
// SIG // dABhAHQAZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3S
// SIG // eQyQwWVfLiw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1
// SIG // pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4p
// SIG // m+Y9G6XUtR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJG
// SIG // KsKKELukqQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD
// SIG // 9MCP80Yr3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L
// SIG // 8giJ1h/DMhji8MUtzluetEk5CsYKwsatruWy2dsViFFF
// SIG // WDgycScaf7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEq
// SIG // KD6CPxNNZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobD
// SIG // HWM2l4bf2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbR
// SIG // BrF1HxS+YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADW
// SIG // oUa9WfOXpQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6
// SIG // IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9az
// SIG // I2h15q/6/IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5P
// SIG // v4BXIqF4ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJ
// SIG // m3ZbCoBIa/15n8G9bW1qyVJzEw16UM0xggSqMIIEpgIB
// SIG // ATCBlTB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQD
// SIG // Ex9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDEx
// SIG // AhMzAAAAZEeElIbbQRk4AAAAAABkMAkGBSsOAwIaBQCg
// SIG // gb4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
// SIG // KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZI
// SIG // hvcNAQkEMRYEFPGULQrAoTX2U5VlT2ka11qftQ8fMF4G
// SIG // CisGAQQBgjcCAQwxUDBOoAyACgBBAGQAUwBEAEuhPoA8
// SIG // aHR0cDovL2Vkd2ViL3NpdGVzL0lTU0VuZ2luZWVyaW5n
// SIG // L0VuZ0Z1bi9TaXRlUGFnZXMvSG9tZS5hc3B4MA0GCSqG
// SIG // SIb3DQEBAQUABIIBADztg2T6c8HvKK7dOVzWe+kagyAP
// SIG // Q7f2ocPaQ5H3rGElrWDJmoWwLkybPnx4Of32UKBE4SJX
// SIG // fpmou35kGSiVi6NNd6TuPhpevptCE2U4C2OT23mcBqNR
// SIG // P8MmGu80hR50IjVmiTGQyBLH6qfOSvKsa/IqG43XGzhR
// SIG // sld/xo5vcWLiwMRSWcK+V/2daNahFCmTiy5XivnZSvNl
// SIG // 4unFESNROkNKBWxTPLQT5B7ETfDzn+NyfP2prIWW+VHz
// SIG // cEN34lOq0USYDTpAmW5LSvncGr2ToX6wGoJkpdaw/oAE
// SIG // fJLQDTWugzZIxKnilg3J2fZd9RTGbvYrL5WtQIDvd4hR
// SIG // BnwnqiqhggIoMIICJAYJKoZIhvcNAQkGMYICFTCCAhEC
// SIG // AQEwgY4wdzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UE
// SIG // AxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBAhMzAAAA
// SIG // rGMW5+NGVbMcAAAAAACsMAkGBSsOAwIaBQCgXTAYBgkq
// SIG // hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
// SIG // BTEPFw0xNjA5MjgxNjM4MDVaMCMGCSqGSIb3DQEJBDEW
// SIG // BBTfqw3OA15aeoqs7cKuOR+I/XAtdzANBgkqhkiG9w0B
// SIG // AQUFAASCAQBE+VaP0K4/aVPcFf9Aby+LxSx7i0Hl5wJ0
// SIG // mgQhF2ZDFIutuQH5klunvrVnigaIlPEuv74MQaSpoIlT
// SIG // xo1brbfaOJ3aSCcfyZ9bH1GxisdpSCa2Q4ImSsMuC4EN
// SIG // nXdveHwsvtqHWFjLWOg6n0tXbws7poRFLbXPzjeMDWBA
// SIG // /ql1I3vfoEF53FMrFECw3b26NBVzE62XsAOosNfnbnwh
// SIG // KmlNrpn5n2LzKC8OVLqUcAJ4TusG0CF8O+pFlARtdiOi
// SIG // wTPW/BdlWDrOUpii3N43x7L2wNe1IntKu6ALoWSiz1mA
// SIG // AdGqspiLFr6p6Q0rJfxyWkdYAZ6JmCSHE/1ziQ94XZIu
// SIG // End signature block
