"use strict";
/*!
  Copyright (C) Microsoft. All rights reserved.
  This library is supported for use in Windows Store apps only.
*/
function setScreenSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setScreenSize(r,i)}function invokeInit(){Ormma.getState()==ORMMA_EVENT_LOADING&&Ormma._setState(ORMMA_STATE_DEFAULT);Ormma._init()}function reportError(n,t){Ormma._throwError(n,t)}function setOrmmaState(n){Ormma._setState(n)}function setOrmmaPlacementType(n){Ormma._setPlacementType(n)}function setOrmmaLocale(n){Ormma._setLocale(n)}function setSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setSize(r,i)}function setMaxSize(n,t){var r=parseInt(n),i;r=r===NaN?-1:r;i=parseInt(t);i=i===NaN?-1:i;Ormma._setMaxSize(r,i)}function setOrientation(n){var t=parseInt(n);t=t===NaN?-1:t;Ormma._setOrientation(t)}function fireShake(){Ormma._shake()}function updateTiltCoords(n,t,i){Ormma._tiltChange({x:n,y:t,z:i})}function fireViewable(n){var t=stringToBoolean(n);Ormma._viewableChange(t)}function viewableDataChange(n){Ormma._viewableDataChange(n)}function setCapability(n,t){Ormma._setCapability(n,stringToBoolean(t))}function stringToBoolean(n){return n.toLowerCase()==="true"?!0:!1}function fireResponse(n,t){var i={url:escape(n),response:escape(t)};Ormma._sendResponse(i)}function setNetwork(n){Ormma._setNetwork(n)}function setSdkVersion(n,t,i){Ormma._setSdkVersion(n,t,i)}function fireClickEvent(){Ormma._clicked()}var ORMMA_STATE_UNKNOWN="unknown",ORMMA_STATE_HIDDEN="hidden",ORMMA_STATE_DEFAULT="default",ORMMA_STATE_EXPANDED="expanded",ORMMA_STATE_RESIZED="resized",ORMMA_STATE_SUSPENDED="suspended",ORMMA_EVENT_ERROR="error",ORMMA_EVENT_HEADING_CHANGE="headingChange",ORMMA_EVENT_KEYBOARD_CHANGE="keyboardChange",ORMMA_EVENT_LOCATION_CHANGE="locationChange",ORMMA_EVENT_NETWORK_CHANGE="networkChange",ORMMA_EVENT_ORIENTATION_CHANGE="orientationChange",ORMMA_EVENT_VIEWABLE_CHANGE="viewableChange",ORMMA_EVENT_READY="ready",ORMMA_EVENT_LOADING="loading",ORMMA_EVENT_RESPONSE="response",ORMMA_EVENT_SCREEN_CHANGE="screenChange",ORMMA_EVENT_SHAKE="shake",ORMMA_EVENT_SIZE_CHANGE="sizeChange",ORMMA_EVENT_STATE_CHANGE="stateChange",ORMMA_EVENT_TILT_CHANGE="tiltChange",MAPLE_EVENT_CLICK="click",MAPLE_EVENT_VIEWABLEDATA_CHANGE="viewableDataChange",ORMMA_FEATURE_SCREEN="screen",ORMMA_FEATURE_ORIENTATION="orientation",ORMMA_FEATURE_LOCATION="location",ORMMA_FEATURE_SMS="sms",ORMMA_FEATURE_PHONE="phone",ORMMA_FEATURE_EMAIL="email",ORMMA_FEATURE_HEADING="heading",ORMMA_FEATURE_SHAKE="shake",ORMMA_FEATURE_TILT="tilt",ORMMA_FEATURE_NETWORK="network",ORMMA_FEATURE_CALENDAR="calendar",ORMMA_FEATURE_CAMERA="camera",ORMMA_FEATURE_MAP="map",ORMMA_FEATURE_AUDIO="audio",ORMMA_FEATURE_VIDEO="video",ORMMA_FEATURE_LEVEL1="level-1",ORMMA_FEATURE_LEVEL2="level-2",ORMMA_FEATURE_LEVEL3="level-3",ORMMA_FEATURE_INLINEVIDEO="inlineVideo",ORMMA_API_VERSION="1.1.0",MRAID_API_VERSION="1.0",MAPLE_MAX_STATE_DATA_SIZE=65536,ORMMA_PLACEMENTTYPE_INLINE="inline",ORMMA_PLACEMENTTYPE_INTERSTITIAL="interstitial",MSG_TYPE_ADRENDERED="rendered",MSG_TYPE_OPEN="web",MSG_TYPE_EXPAND="expand",MSG_TYPE_CLOSE="close",MSG_TYPE_RESIZE="resize",MSG_TYPE_HIDE="hide",MSG_TYPE_SHOW="show",MSG_TYPE_SETEXPANDPROPERTIES="setexpandproperties",MSG_TYPE_SETUSERENGAGED="setuserengaged",MSG_TYPE_TILT="tilt",MSG_TYPE_SHAKE="shake",MSG_TYPE_LISTENER="listener",MSG_TYPE_VALUESTART="start",MSG_TYPE_VALUESTOP="stop",MSG_TYPE_GETTILT="gettilt",MSG_TYPE_GETORIENTATION="getorientation",MSG_TYPE_REFRESH="refresh",MSG_TYPE_REQUEST="request",MSG_TYPE_VIEWABLECHANGE="viewableChange",MSG_TYPE_VIEWABLEDATACHANGE="viewableDataChange",MSG_TYPE_ERROR="error",MSG_TYPE_USECUSTOMCLOSE="usecustomclose";(function(){function f(){this.listeners=[]}function n(){}function u(n){return typeof n=="undefined"||n===null||n<=0?!1:!0}function t(n){window.msAdSDK&&typeof window.msAdSDK.notify=="function"?window.msAdSDK.notify(n):window.external.notify(n)}function r(t,r){if(n("raising event "+t+" with data "+r),i.listeners[t]!==null&&typeof i.listeners[t]!="undefined")try{var f=i.listeners[t].slice(),u;switch(t){case ORMMA_EVENT_ERROR:for(u=0;u<f.length;u++)f[u](r.message,r.action);break;case ORMMA_EVENT_NETWORK_CHANGE:for(u=0;u<f.length;u++)f[u](r.online,r.connection);break;case ORMMA_EVENT_ORIENTATION_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_READY:for(u=0;u<f.length;u++)f[u]();break;case ORMMA_EVENT_SCREEN_CHANGE:for(u=0;u<f.length;u++)f[u](r.width,r.height);break;case ORMMA_EVENT_SHAKE:for(u=0;u<f.length;u++)f[u]();break;case ORMMA_EVENT_SIZE_CHANGE:for(u=0;u<f.length;u++)f[u](r.width,r.height);break;case ORMMA_EVENT_STATE_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_TILT_CHANGE:for(u=0;u<f.length;u++)f[u](r.x,r.y,r.z);break;case ORMMA_EVENT_VIEWABLE_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_RESPONSE:for(u=0;u<f.length;u++)f[u](unescape(r.url),unescape(r.response));break;case MAPLE_EVENT_CLICK:for(u=0;u<f.length;u++)f[u]();break;case MAPLE_EVENT_VIEWABLEDATA_CHANGE:for(u=0;u<f.length;u++)f[u](r);break;case ORMMA_EVENT_HEADING_CHANGE:case ORMMA_EVENT_KEYBOARD_CHANGE:case ORMMA_EVENT_LOCATION_CHANGE:default:return!1}}catch(e){n("exception thrown while firing event: "+e.message)}else n("no listeners for event "+t)}var i=new f;window.ORMMA=window.ormma=window.Ormma=window.MAPLE=window.maple=window.Maple={_maxSize:{width:0,height:0},_dimensions:{},_defaultDimensions:{},_screenSize:null,_tiltCapability:!1,_shakeCapability:!1,_expandProperties:{width:0,height:0,useCustomClose:!1,lockOrientation:!1,isModal:!0},_shakeProperties:{},_resizeProperties:{transition:"none"},_placementType:ORMMA_PLACEMENTTYPE_INLINE,_state:ORMMA_EVENT_LOADING,_locale:null,_location:null,_orientation:-1,_lastTiltCoords:{x:0,y:0,z:0},_lastNetworkState:ORMMA_STATE_UNKNOWN,_sdkInfo:null,_msOrientationModes:{portaitPrimary:{ieProperty:"portrait-primary",orientationDegrees:0},landscapePrimary:{ieProperty:"landscape-primary",orientationDegrees:270},portaitSecondary:{ieProperty:"portrait-secondary",orientationDegrees:180},landscapeSecondary:{ieProperty:"landscape-secondary",orientationDegrees:90},unknown:{ieProperty:"",orientationDegrees:-1}},addEventListener:function(r,u){if((i.listeners[r]===null||typeof i.listeners[r]=="undefined")&&(i.listeners[r]=[]),r!==ORMMA_EVENT_TILT_CHANGE||this._tiltCapability){if(r===ORMMA_EVENT_SHAKE&&!this._shakeCapability){this._throwError("shake","shake capability is not supported, event listener not added");return}}else{this._throwError("tilt","tilt capability is not supported, event listener not added");return}n("adding listener for "+r);i.listeners[r].push(u);r===ORMMA_EVENT_TILT_CHANGE?t(MSG_TYPE_TILT+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_SHAKE?t(MSG_TYPE_SHAKE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_ORIENTATION_CHANGE?t(MSG_TYPE_GETORIENTATION+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===ORMMA_EVENT_VIEWABLE_CHANGE?t(MSG_TYPE_VIEWABLECHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART):r===MAPLE_EVENT_VIEWABLEDATA_CHANGE&&t(MSG_TYPE_VIEWABLEDATACHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTART)},removeEventListener:function(r,u){if(n("removing listener for "+r),i.listeners[r]!==null&&typeof i.listeners[r]!="undefined"){if(u===undefined||u===null||u==="")i.listeners[r].length=0;else for(var e=i.listeners[r],f=0;f<e.length;f++)if(e[f]===u){e.splice(f,1);break}if(i.listeners[r]===null||typeof i.listeners[r]=="undefined"||i.listeners[r].length===0)if(r===ORMMA_EVENT_TILT_CHANGE){if(!this._tiltCapability){this._throwError("tilt","tilt capability is not supported, no event listener");return}n("stopping tilt device for event: "+r+" (no more client listeners)");t(MSG_TYPE_TILT+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)}else if(r===ORMMA_EVENT_SHAKE){if(!this._shakeCapability){this._throwError("shake","shake capability is not supported, no event listener");return}n("stopping shake device for event: "+r+" (no more client listeners)");t(MSG_TYPE_SHAKE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)}else r===ORMMA_EVENT_ORIENTATION_CHANGE?(n("stopping orientation changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_GETORIENTATION+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)):r===ORMMA_EVENT_VIEWABLE_CHANGE?(n("stopping viewable changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_VIEWABLECHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP)):r===MAPLE_EVENT_CLICK?n("stopping clickEvent : "+r+" (no more client listeners)"):r===MAPLE_EVENT_VIEWABLEDATA_CHANGE&&(n("stopping viewable data changed event: "+r+" (no more client listeners)"),t(MSG_TYPE_VIEWABLEDATACHANGE+":"+MSG_TYPE_LISTENER+"="+MSG_TYPE_VALUESTOP))}},close:function(){n("sending close request");t(MSG_TYPE_CLOSE)},expand:function(i,r){var u,f;if(!(this.getState()===ORMMA_STATE_DEFAULT||this.getState()===ORMMA_STATE_RESIZED)){reportError("expand","can only expand from resized or default states");return}(typeof i=="undefined"||i===null)&&(i="");(typeof r=="undefined"||r===null)&&(r=!0);typeof this._expandProperties=="object"&&(u=JSON.stringify(this._expandProperties),t(MSG_TYPE_SETEXPANDPROPERTIES+":"+u));n("sending expand request");f={url:i,islegacy:r};t(MSG_TYPE_EXPAND+":"+JSON.stringify(f))},getDefaultPosition:function(){return this._defaultDimensions},getExpandProperties:function(){return this._expandProperties?this._expandProperties:Ormma._expandProperties},getNetwork:function(){return this._lastNetworkState},getOrientation:function(){var n=this._msOrientationToOrmmaDegrees(window.screen.msOrientation);return this._orientation=this._orientation===n?this._orientation:n,this._orientation},getPlacementType:function(){return this._placementType},getScreenSize:function(){return this._screenSize===null&&(this._screenSize={width:screen.availWidth,height:screen.availHeight}),this._screenSize},getShakeProperties:function(){return this._shakeProperties},getSize:function(){return typeof this._dimensions=="undefined"&&(this._dimensions={}),this._dimensions},getState:function(){return this._state},getTilt:function(){if(n("calling getTilt"),!this._tiltCapability){this._throwError("tilt","tilt capability is not supported");return}return t(MSG_TYPE_TILT+":"+MSG_TYPE_GETTILT+"="+MSG_TYPE_REFRESH),this._lastTiltCoords},getVersion:function(){return ORMMA_API_VERSION},hide:function(){n("calling hide");t(MSG_TYPE_HIDE)},isViewable:function(){n("[not impl] isViewable called")},open:function(i){n("sending website request: "+i);var r=JSON.stringify({url:i});t(MSG_TYPE_OPEN+":"+r)},request:function(n,i){var r={url:n,display:typeof i!="undefined"&&i!==null?i:"ignore"};return t(MSG_TYPE_REQUEST+":"+JSON.stringify(r)),!1},resize:function(i,r){if(i>this._maxSize.width||i<0){this._throwError("resize","width is greater than max allowed width ("+this._maxSize.width+") or less than zero.");return}if(r>this._maxSize.height||r<0){this._throwError("resize","height is greater than max allowed height  ("+this._maxSize.height+") or less than zero.");return}n("calling resize:width="+i+"&height="+r);var u={width:i,height:r};t(MSG_TYPE_RESIZE+":"+JSON.stringify(u))},setExpandProperties:function(i){var r,f;this._expandProperties=typeof i!="object"?{}:i;r=typeof this.getScreenSize=="function"?this.getScreenSize():window.ormma.getScreenSize();this._expandProperties.width=u(this._expandProperties.width)&&this._expandProperties.width<r.width?this._expandProperties.width:r.width;this._expandProperties.height=u(this._expandProperties.height)&&this._expandProperties.height<r.height?this._expandProperties.height:r.height;this._expandProperties.useCustomClose=typeof this._expandProperties.useCustomClose=="undefined"?!1:this._expandProperties.useCustomClose;this._expandProperties.lockOrientation=typeof this._expandProperties.lockOrientation=="undefined"?!1:this._expandProperties.lockOrientation;this._expandProperties.isModal=!0;f=JSON.stringify(this._expandProperties);n("setting expand properties: "+f);t(MSG_TYPE_SETEXPANDPROPERTIES+":"+f)},setShakeProperties:function(t){this._shakeProperties=typeof t!="object"?{}:t;n("setting shake properties: "+JSON.stringify(this._shakeProperties))},show:function(){n("calling show");t(MSG_TYPE_SHOW)},supports:function(n){switch(n){case ORMMA_FEATURE_SCREEN:case ORMMA_FEATURE_ORIENTATION:case ORMMA_FEATURE_LEVEL1:case ORMMA_FEATURE_LEVEL2:case ORMMA_FEATURE_NETWORK:case ORMMA_FEATURE_INLINEVIDEO:return!0;case ORMMA_FEATURE_SHAKE:return this._shakeCapability;case ORMMA_FEATURE_TILT:return this._tiltCapability;case ORMMA_FEATURE_PHONE:case ORMMA_FEATURE_SMS:case ORMMA_FEATURE_EMAIL:case ORMMA_FEATURE_LOCATION:case ORMMA_FEATURE_HEADING:case ORMMA_FEATURE_CALENDAR:case ORMMA_FEATURE_AUDIO:case ORMMA_FEATURE_VIDEO:case ORMMA_FEATURE_LEVEL3:default:return!1}},useCustomClose:function(i){typeof i=="boolean"?(n("calling usecustomclose:"+i),typeof this._expandProperties=="object"&&(this._expandProperties.useCustomClose=i),t(MSG_TYPE_USECUSTOMCLOSE+":"+i)):reportError("useCustomClose","parameter 'flag' is not a boolean value")},adAnchorReady:function(){var n=document.getElementById("msMainAdDiv");n!==null&&(n.style.visibility="visible");t(MSG_TYPE_ADRENDERED)},adError:function(n,i){var r,u;r=typeof n=="string"&&n!==null?n:"unknown action";u=typeof i=="string"&&i!==null?i:"an unknown error occurred.";t(MSG_TYPE_ERROR+":"+JSON.stringify({action:r,message:u}))},getLocale:function(){if(this._locale!==null)return this._locale},getSdkVersion:function(){if(this._sdkInfo!==null)return this._sdkInfo},hasListenerForClickEvent:function(){return typeof i.listeners[MAPLE_EVENT_CLICK]!="undefined"&&i.listeners[MAPLE_EVENT_CLICK]!==null&&i.listeners[MAPLE_EVENT_CLICK].length>0?!0:!1},setUserEngaged:function(i){this._isUserEngaged=typeof i=="boolean"?i:!1;n("setting user engaged: "+this._isUserEngaged);t(MSG_TYPE_SETUSERENGAGED+":engaged="+this._isUserEngaged)},_clicked:function(){r(MAPLE_EVENT_CLICK,null)},_tiltChange:function(n){this._lastTiltCoords=n;r(ORMMA_EVENT_TILT_CHANGE,n)},_shake:function(){r(ORMMA_EVENT_SHAKE)},_viewableChange:function(n){window.mraid._isViewable=n;r(ORMMA_EVENT_VIEWABLE_CHANGE,n)},_viewableDataChange:function(n){r(MAPLE_EVENT_VIEWABLEDATA_CHANGE,n)},_sendResponse:function(n){r(ORMMA_EVENT_RESPONSE,n)},_throwError:function(n,t){var i={message:t,action:n};r(ORMMA_EVENT_ERROR,i)},_init:function(){n("Ormma is ready");r(ORMMA_EVENT_READY,null);typeof window.ORMMAReady=="function"&&(n("Ormma calling ORMMAReady()"),window.ORMMAReady())},_setOrientation:function(n){var t=this._orientation;this._orientation=n;t!==this._orientation&&r(ORMMA_EVENT_ORIENTATION_CHANGE,this._orientation)},_setPlacementType:function(n){n===ORMMA_PLACEMENTTYPE_INLINE?this._placementType=n:n===ORMMA_PLACEMENTTYPE_INTERSTITIAL&&(this._placementType=n)},_setState:function(n){var t=this._state;this._state=n;t!==n&&r(ORMMA_EVENT_STATE_CHANGE,this._state)},_setLocale:function(n){this._locale=n},_setSize:function(n,t){typeof this._dimensions=="undefined"&&(this._dimensions={});var i=typeof this._dimensions.width=="undefined"?0:this._dimensions.width,u=typeof this._dimensions.height=="undefined"?0:this._dimensions.height;this._dimensions.width=n;this._dimensions.height=t;(i!==n||u!==t)&&r(ORMMA_EVENT_SIZE_CHANGE,this._dimensions)},_setSdkVersion:function(n,t,i){this._sdkInfo={sdkVersion:n,client:t,runtimeType:i,appName:navigator.appName,appVersion:navigator.appVersion,userAgent:navigator.userAgent,platform:navigator.platform}},_setCapability:function(n,t){typeof t=="boolean"&&(n===ORMMA_FEATURE_TILT?this._tiltCapability=t:n===ORMMA_FEATURE_SHAKE&&(this._shakeCapability=t))},_setMaxSize:function(n,t){typeof this._maxSize=="undefined"&&(this._maxSize={});this._maxSize.width=n;this._maxSize.height=t},_setScreenSize:function(n,t){(this._screenSize===null||typeof this._screenSize=="undefined")&&(this._screenSize={});var i=typeof this._screenSize.width=="undefined"?0:this._screenSize.width,u=typeof this._screenSize.height=="undefined"?0:this._screenSize.height;this._screenSize.width=n;this._screenSize.height=t;this._expandProperties.width===i&&(this._expandProperties.width=n);this._expandProperties.height===u&&(this._expandProperties.height=t);this.setExpandProperties(this._expandProperties);(i!==this._screenSize.width||u!==this._screenSize.height)&&r(ORMMA_EVENT_SCREEN_CHANGE,this._screenSize)},_setNetwork:function(t){n("setting network state: "+t);typeof this._lastNetworkState=="undefined"&&(this._lastNetworkState="");t!==this._lastNetworkState&&(this._lastNetworkState=t,r(ORMMA_EVENT_NETWORK_CHANGE,{online:t!=="offline",connection:t}))},_msOrientationToOrmmaDegrees:function(n){switch(n){case this._msOrientationModes.landscapePrimary.ieProperty:return this._msOrientationModes.landscapePrimary.orientationDegrees;case this._msOrientationModes.landscapeSecondary.ieProperty:return this._msOrientationModes.landscapeSecondary.orientationDegrees;case this._msOrientationModes.portaitSecondary.ieProperty:return this._msOrientationModes.portaitSecondary.orientationDegrees;case this._msOrientationModes.portaitPrimary.ieProperty:return this._msOrientationModes.portaitPrimary.orientationDegrees;default:return this._msOrientationModes.unknown.orientationDegrees}}};window.mraid=window.MRAID=window.Mraid={_isViewable:!1,addEventListener:function(n,t){this._mraidSupportedEvts===null&&(this._mraidSupportedEvts=this._initEventList());this._mraidSupportedEvts[n]&&window.ormma.addEventListener(n,t)},removeEventListener:function(n,t){this._mraidSupportedEvts===null&&(this._mraidSupportedEvts=this._initEventList());this._mraidSupportedEvts[n]&&window.ormma.removeEventListener(n,t)},expand:function(n){typeof n=="undefined"||n===null?window.ormma.expand("",!1):window.ormma.expand(n,!1)},getState:function(){return window.ormma._state},getVersion:function(){return MRAID_API_VERSION},isViewable:function(){return window.mraid._isViewable},_mraidSupportedEvts:null,_initEventList:function(){var n=[];return n[ORMMA_EVENT_ERROR]=n[ORMMA_EVENT_READY]=n[ORMMA_EVENT_STATE_CHANGE]=n[MAPLE_EVENT_VIEWABLEDATA_CHANGE]=n[ORMMA_EVENT_VIEWABLE_CHANGE]=!0,n},supports:function(n){return window.ormma.supports(n)},getSize:function(){return window.ormma.getSize()},open:function(n){return window.ormma.open(n)},close:function(){return window.ormma.close()},getExpandProperties:function(){return window.ormma.getExpandProperties()},getPlacementType:function(){return window.ormma.getPlacementType()},setExpandProperties:function(n){return window.ormma.setExpandProperties(n)},useCustomClose:function(n){return window.ormma.useCustomClose(n)}}})();
// SIG // Begin signature block
// SIG // MIIdogYJKoZIhvcNAQcCoIIdkzCCHY8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFOh8FgOz4NZo
// SIG // O9uTj4sYTa8OhkDgoIIYZDCCBMMwggOroAMCAQICEzMA
// SIG // AACsYxbn40ZVsxwAAAAAAKwwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDUwMzE3
// SIG // MTMyM1oXDTE3MDgwMzE3MTMyM1owgbMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsT
// SIG // Hm5DaXBoZXIgRFNFIEVTTjpDMEY0LTMwODYtREVGODEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBAJ8h3YTccknLV/hvi0hiAhANf1YT1ZtfcdeBRgUA
// SIG // lKkNQEzmvMz9WRplOiTlI/ECx5uEgMJSr6LBi/KNN1XK
// SIG // QjbDftNeYzF24YT+8DE2aQA05eRMPO+nUqoCkcRLbmh4
// SIG // +LCbt1tX4SfWKpsHqflc+fo3FEFdiGSwcONZpljGhi2o
// SIG // aWi27pflzme8Itvqn06z1WKQd74VTMGqSxJDN9obDlH5
// SIG // fqGb7gH0cDwRcWPxptJ2XE2wddo0q/EKwRe8n9Xv9yko
// SIG // qpXnItxm0mU/PeiznK+235uZzV/HxFqMOlmVgayOiyj8
// SIG // fbd3HsuLc9KQHXV9jeiwErd0NB4Ozf87IDmL65cCAwEA
// SIG // AaOCAQkwggEFMB0GA1UdDgQWBBQhVywB7YNQaGndwU1p
// SIG // q42rT5Q3YjAfBgNVHSMEGDAWgBQjNPjZUkZwCu1A+3b7
// SIG // syuwwzWzDzBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
// SIG // Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
// SIG // cy9NaWNyb3NvZnRUaW1lU3RhbXBQQ0EuY3JsMFgGCCsG
// SIG // AQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL3d3
// SIG // dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3Nv
// SIG // ZnRUaW1lU3RhbXBQQ0EuY3J0MBMGA1UdJQQMMAoGCCsG
// SIG // AQUFBwMIMA0GCSqGSIb3DQEBBQUAA4IBAQBGNopaApng
// SIG // TXZuCD1daUIu3+BLDZqLVDHp+Q/A4OKzixPSZHdJTTi+
// SIG // XIZlivnfQSxuUqrD9Ef4KqYeIRxWTOC1R1K0sUHEC1gR
// SIG // In6zNgXjdBumKUYhge550KqvOvjcF/daS4SeSwcyaPhL
// SIG // nFhShZhAVyzAS/OX8grrApNEaMHR6aoebN84ZDIIxV/n
// SIG // F1syV1C3xnxD7wlwyiIMbHOZFGpWInv5pAim6VlxFuoD
// SIG // fhTTyk274x3AsbXH/ZlXqpQOY6ExXviWzMoLTk3l9DJX
// SIG // +K07wq395ANM7ESS/8uSXYoXcUj/Jyl+R9ENglpgw2Ps
// SIG // b28fbS3qrP2xE6WjM+yv/wH+MIIGBzCCA++gAwIBAgIK
// SIG // YRZoNAAAAAAAHDANBgkqhkiG9w0BAQUFADBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDcwNDAz
// SIG // MTI1MzA5WhcNMjEwNDAzMTMwMzA5WjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
// SIG // DwAwggEKAoIBAQCfoWyx39tIkip8ay4Z4b3i48WZUSNQ
// SIG // rc7dGE4kD+7Rp9FMrXQwIBHrB9VUlRVJlBtCkq6YXDAm
// SIG // 2gBr6Hu97IkHD/cOBJjwicwfyzMkh53y9GccLPx754gd
// SIG // 6udOo6HBI1PKjfpFzwnQXq/QsEIEovmmbJNn1yjcRlOw
// SIG // htDlKEYuJ6yGT1VSDOQDLPtqkJAwbofzWTCd+n7Wl7Po
// SIG // IZd++NIT8wi3U21StEWQn0gASkdmEScpZqiX5NMGgUqi
// SIG // +YSnEUcUCYKfhO1VeP4Bmh1QCIUAEDBG7bfeI0a7xC1U
// SIG // n68eeEExd8yb3zuDk6FhArUdDbH895uyAc4iS1T/+QXD
// SIG // wiALAgMBAAGjggGrMIIBpzAPBgNVHRMBAf8EBTADAQH/
// SIG // MB0GA1UdDgQWBBQjNPjZUkZwCu1A+3b7syuwwzWzDzAL
// SIG // BgNVHQ8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwgZgG
// SIG // A1UdIwSBkDCBjYAUDqyCYEBWJ5flJRP8KuEKU5VZ5KSh
// SIG // Y6RhMF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJ
// SIG // kiaJk/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eYIQea0WoUqgpa1Mc1j0BxMuZTBQBgNVHR8ESTBHMEWg
// SIG // Q6BBhj9odHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtp
// SIG // L2NybC9wcm9kdWN0cy9taWNyb3NvZnRyb290Y2VydC5j
// SIG // cmwwVAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjho
// SIG // dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRz
// SIG // L01pY3Jvc29mdFJvb3RDZXJ0LmNydDATBgNVHSUEDDAK
// SIG // BggrBgEFBQcDCDANBgkqhkiG9w0BAQUFAAOCAgEAEJeK
// SIG // w1wDRDbd6bStd9vOeVFNAbEudHFbbQwTq86+e4+4LtQS
// SIG // ooxtYrhXAstOIBNQmd16QOJXu69YmhzhHQGGrLt48ovQ
// SIG // 7DsB7uK+jwoFyI1I4vBTFd1Pq5Lk541q1YDB5pTyBi+F
// SIG // A+mRKiQicPv2/OR4mS4N9wficLwYTp2OawpylbihOZxn
// SIG // LcVRDupiXD8WmIsgP+IHGjL5zDFKdjE9K3ILyOpwPf+F
// SIG // ChPfwgphjvDXuBfrTot/xTUrXqO/67x9C0J71FNyIe4w
// SIG // yrt4ZVxbARcKFA7S2hSY9Ty5ZlizLS/n+YWGzFFW6J1w
// SIG // lGysOUzU9nm/qhh6YinvopspNAZ3GmLJPR5tH4LwC8cs
// SIG // u89Ds+X57H2146SodDW4TsVxIxImdgs8UoxxWkZDFLyz
// SIG // s7BNZ8ifQv+AeSGAnhUwZuhCEl4ayJ4iIdBD6Svpu/RI
// SIG // zCzU2DKATCYqSCRfWupW76bemZ3KOm+9gSd0BhHudiG/
// SIG // m4LBJ1S2sWo9iaF2YbRuoROmv6pH8BJv/YoybLL+31HI
// SIG // jCPJZr2dHYcSZAI9La9Zj7jkIeW1sMpjtHhUBdRBLlCs
// SIG // lLCleKuzoJZ1GtmShxN1Ii8yqAhuoFuMJb+g74TKIdbr
// SIG // Hk/Jmu5J4PcBZW+JC33Iacjmbuqnl84xKf8OxVtc2E0b
// SIG // odj6L54/LlUWa8kTo/0wggYQMIID+KADAgECAhMzAAAA
// SIG // ZEeElIbbQRk4AAAAAABkMA0GCSqGSIb3DQEBCwUAMH4x
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
// SIG // c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcNMTUx
// SIG // MDI4MjAzMTQ2WhcNMTcwMTI4MjAzMTQ2WjCBgzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjENMAsGA1UECxMETU9QUjEeMBwG
// SIG // A1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMIIBIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAky7a2OY+
// SIG // mNkbD2RfTahYTRQ793qE/DwRMTrvicJKLUGlSF3dEp7v
// SIG // q2YoNNV9KlV7TE2K8sDxstNSFYu2swi4i1AL3X/7agmg
// SIG // 3GcExPHfvHUYIEC+eCyZVt3u9S7dPkL5Wh8wrgEUirCC
// SIG // tVGg4m1l/vcYCo0wbU06p8XzNi3uXyygkgCxHEziy/f/
// SIG // JCV/14/A3ZduzrIXtsccRKckyn6B5uYxuRbZXT7RaO6+
// SIG // zUjQhiyu3A4hwcCKw+4bk1kT9sY7gHIYiFP7q78wPqB3
// SIG // vVKIv3rY6LCTraEbjNR+phBQEL7hyBxk+ocu+8RHZhbA
// SIG // hHs2r1+6hURsAg8t4LAOG6I+JQIDAQABo4IBfzCCAXsw
// SIG // HwYDVR0lBBgwFgYIKwYBBQUHAwMGCisGAQQBgjdMCAEw
// SIG // HQYDVR0OBBYEFFhWcQTwvbsz9YNozOeARvdXr9IiMFEG
// SIG // A1UdEQRKMEikRjBEMQ0wCwYDVQQLEwRNT1BSMTMwMQYD
// SIG // VQQFEyozMTY0Mis0OWU4YzNmMy0yMzU5LTQ3ZjYtYTNi
// SIG // ZS02YzhjNDc1MWM0YjYwHwYDVR0jBBgwFoAUSG5k5VAF
// SIG // 04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZD
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // cmwvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // bDBhBggrBgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
// SIG // dHMvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IC
// SIG // AQCI4gxkQx3dXK6MO4UktZ1A1r1mrFtXNdn06DrARZkQ
// SIG // Tdu0kOTLdlGBCfCzk0309RLkvUgnFKpvLddrg9TGp3n8
// SIG // 0yUbRsp2AogyrlBU+gP5ggHFi7NjGEpj5bH+FDsMw9Py
// SIG // gLg8JelgsvBVudw1SgUt625nY7w1vrwk+cDd58TvAyJQ
// SIG // FAW1zJ+0ySgB9lu2vwg0NKetOyL7dxe3KoRLaztUcqXo
// SIG // YW5CkI+Mv3m8HOeqlhyfFTYxPB5YXyQJPKQJYh8zC9b9
// SIG // 0JXLT7raM7mQ94ygDuFmlaiZ+QSUR3XVupdEngrmZgUB
// SIG // 5jX13M+Pl2Vv7PPFU3xlo3Uhj1wtupNC81epoxGhJ0tR
// SIG // uLdEajD/dCZ0xIniesRXCKSC4HCL3BMnSwVXtIoj/QFy
// SIG // mFYwD5+sAZuvRSgkKyD1rDA7MPcEI2i/Bh5OMAo9App4
// SIG // sR0Gp049oSkXNhvRi/au7QG6NJBTSBbNBGJG8Qp+5QTh
// SIG // KoQUk8mj0ugr4yWRsA9JTbmqVw7u9suB5OKYBMUN4hL/
// SIG // yI+aFVsE/KJInvnxSzXJ1YHka45ADYMKAMl+fLdIqm3n
// SIG // x6rIN0RkoDAbvTAAXGehUCsIod049A1T3IJyUJXt3OsT
// SIG // d3WabhIBXICYfxMg10naaWcyUePgW3+VwP0XLKu4O1+8
// SIG // ZeGyaDSi33GnzmmyYacX3BTqMDCCB3owggVioAMCAQIC
// SIG // CmEOkNIAAAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29m
// SIG // dCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEx
// SIG // MB4XDTExMDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVow
// SIG // fjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWlj
// SIG // cm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIw
// SIG // DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQ
// SIG // HC6t2G6qghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/D
// SIG // DB7dN2vGEtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRs
// SIG // r55JnOloXtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ2
// SIG // 6DJSJhIv56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea6
// SIG // 4DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3
// SIG // vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuG
// SIG // G9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGy
// SIG // r5I4ftKdgCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOG
// SIG // jfdf8NBSv4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKu
// SIG // HCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0Xpb
// SIG // L9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/p
// SIG // I0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkw
// SIG // p6uO3+xbn6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4Dm
// SIG // imJ4X7IvhNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJ
// SIG // TMXUpUMvdJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSW
// SIG // sLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEE
// SIG // AYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQw
// SIG // WgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEF
// SIG // BQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2Vy
// SIG // QXV0MjAxMV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGX
// SIG // MIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEW
// SIG // M2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
// SIG // ZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0
// SIG // HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMA
// SIG // dABhAHQAZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3S
// SIG // eQyQwWVfLiw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1
// SIG // pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4p
// SIG // m+Y9G6XUtR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJG
// SIG // KsKKELukqQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD
// SIG // 9MCP80Yr3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L
// SIG // 8giJ1h/DMhji8MUtzluetEk5CsYKwsatruWy2dsViFFF
// SIG // WDgycScaf7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEq
// SIG // KD6CPxNNZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobD
// SIG // HWM2l4bf2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbR
// SIG // BrF1HxS+YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADW
// SIG // oUa9WfOXpQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6
// SIG // IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9az
// SIG // I2h15q/6/IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5P
// SIG // v4BXIqF4ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJ
// SIG // m3ZbCoBIa/15n8G9bW1qyVJzEw16UM0xggSqMIIEpgIB
// SIG // ATCBlTB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQD
// SIG // Ex9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDEx
// SIG // AhMzAAAAZEeElIbbQRk4AAAAAABkMAkGBSsOAwIaBQCg
// SIG // gb4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
// SIG // KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZI
// SIG // hvcNAQkEMRYEFFZB0lJiphJyXRCgh1+x5+9FBuBtMF4G
// SIG // CisGAQQBgjcCAQwxUDBOoAyACgBBAGQAUwBEAEuhPoA8
// SIG // aHR0cDovL2Vkd2ViL3NpdGVzL0lTU0VuZ2luZWVyaW5n
// SIG // L0VuZ0Z1bi9TaXRlUGFnZXMvSG9tZS5hc3B4MA0GCSqG
// SIG // SIb3DQEBAQUABIIBAEH7KbZq4o7DXmr8FhOFRQgfd+V3
// SIG // B6/uvB6VfUBHip+8XuDgymQyKdx8bFEwdL7M22sGJJp+
// SIG // 2wlCy4TGut81uneAxEKSlYfyrcuyh58hSsOlDEHG5h+q
// SIG // +YucEDW4nM0fsFP6r8wbKd2NAwC1isK1mKr+IecpnTwm
// SIG // EwFmX5e3UWNbECBTPWT6lJzho3po8OYz9DEuo1jT53/j
// SIG // IUJbzFbJUs/APFBrD72Y0uBlIosZxjUGtR1jZHx9sDT/
// SIG // 3Cav226od4JcNqw3iwKyPsF1n+brmkhQP5J3OnLfDld+
// SIG // Pv62HRAY3qs6AyUu4hW8y5vQt6iSIPmbbooHWHi/lS7k
// SIG // 618XctShggIoMIICJAYJKoZIhvcNAQkGMYICFTCCAhEC
// SIG // AQEwgY4wdzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UE
// SIG // AxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBAhMzAAAA
// SIG // rGMW5+NGVbMcAAAAAACsMAkGBSsOAwIaBQCgXTAYBgkq
// SIG // hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
// SIG // BTEPFw0xNjA5MjgxNjM4MDVaMCMGCSqGSIb3DQEJBDEW
// SIG // BBSRTPL6+wIkxnDNZ3MUxfj3zD9upDANBgkqhkiG9w0B
// SIG // AQUFAASCAQAMnuQLahY0TaPa9+HdcRme1juTAp2hd2lu
// SIG // e1jsIJV8bIk/KB2TfpXWIgHh4rmtX3ni+9a4uYt7/TOB
// SIG // zxNHQ3ziHl5X17xd8rSN1xkhte/Oewfn2DTKP8t9uwjI
// SIG // LLpyRpeEaPlimIos6FXkmQJPLdbvTLrIVjzrPsL0vLM/
// SIG // 1EsbTJPe4NKXfQTeNJNYNhplnkGX+JN4YfDq3OOPBMbS
// SIG // Rm4evwKPCtd0OEmAydknF317OeXv3nUTSBF3IUgWDmoZ
// SIG // bys4P52dSBCbHQl1H3dF+8RajoYF5fZSBRF+DTIKs8Yf
// SIG // Pl0ezctYXcombZakwdD8yXPObcu7+X1AqvFGyvSJa7ZG
// SIG // End signature block
