/*!
  Copyright (C) Microsoft. All rights reserved.
  This library is supported for use in Windows Store apps only.
*/
(function(){"use strict";function s(){this._listeners=[];this._adSize={};this._setSdkVersion("unknown","unknown","unknown")}var r=2,e=0,o=r+"."+e,n;window.onerror=function(n,t,i){try{console.error("[msg:"+n+"][url:"+t+"][lineNumber:"+i+"]");typeof _msVpaidImpl=="function"&&_msVpaidImpl.reportAdError("unhandled JS exception: "+n)}catch(r){}return!0};window.onload=function(){if(typeof getVPAIDAd!="function"){_msVpaidImpl.reportAdError("getVPAIDAd function not defined");return}var t=getVPAIDAd();if(!t){_msVpaidImpl.reportAdError("getVPAIDAd did not return an ad");return}window._msVpaidInstance=new n(t)};window._msReceiveMessageFromAdSdk=function(t){n.log("message from SDK: "+t);window._msVpaidInstance&&window._msVpaidInstance.receiveMessageFromAdSdk(t);window.Maple&&window.Maple.receiveMessageFromAdSdk(t)};n=function(t){if(n.log("instantiating VpaidImpl"),this._creative=t,this._adParameters=null,!n.isValidVpaidCreative(t)){n.reportAdError("ad is not a valid VPAID creative");return}var i=t.handshakeVersion(o);if(!n.isVersionSupported(i)){n.reportAdError("ad requires VPAID version "+i+", sdk supports "+o);return}this._setupEventHandlers(this._creative)};n.prototype={DEFAULT_DESIRED_BITRATE:2e3,initAd:function(t,i,r,u,f,e){n.log("initializing vpaid ad");e||(e={slot:document.querySelector("#msVpaidSlot"),videoSlot:document.querySelector("#msVpaidVideo")});this._creative.initAd(t,i,r,u,f,e)},receiveMessageFromAdSdk:function(t){var u,f,o;if(t&&typeof t=="string"){var r=t,i=null,e=null;try{u=r.indexOf(":");u<0?i=r:(i=r.substr(0,u),e=r.substr(u+1));i==="InitAd"?this._receiveMessageInitAd(e):i==="StartAd"?this.startAd():i==="StopAd"?this.stopAd():i==="PauseAd"?this.pauseAd():i==="ResumeAd"?this.resumeAd():i==="ResizeAd"?(f=JSON.parse(e),this.resizeAd(f.width,f.height,f.viewMode)):i==="SetAdVolume"&&(o=50,this.setAdVolume(o))}catch(s){n.reportAdError("error handling message of type "+i)}}},_receiveMessageInitAd:function(t){try{var i=JSON.parse(t),r=typeof i.desiredBitrate=="number"?i.desiredBitrate:this.DEFAULT_DESIRED_BITRATE,u=typeof i.width=="number"?i.width:0,f=typeof i.height=="number"?i.height:0,e=typeof i.viewMode=="string"?i.viewMode:"fullscreen",o={AdParameters:i.adParameters};this.initAd(u,f,e,r,o,null)}catch(s){n.reportAdError("unable to parse JSON for initAd")}},setAdVolume:function(n){this._creative.setAdVolume(n)},startAd:function(){n.log("startAd");this._creative.startAd()},stopAd:function(){this._creative.stopAd()},resizeAd:function(t,i,r){n.log("resizing ad to "+t+" x "+i+", "+r);this._creative.resizeAd(t,i,r)},pauseAd:function(){this._creative.pauseAd()},resumeAd:function(){this._creative.resumeAd()},_setupEventHandlers:function(t){t&&(n.log("adding event handlers"),t.subscribe(this._adStartedHandler,"AdStarted",this),t.subscribe(this._adStoppedHandler,"AdStopped",this),t.subscribe(this._adSkippedHandler,"AdSkipped",this),t.subscribe(this._adLoadedHandler,"AdLoaded",this),t.subscribe(this._adLinearChangeHandler,"AdLinearChange",this),t.subscribe(this._adSizeChangeHandler,"AdSizeChange",this),t.subscribe(this._adExpandedChangeHandler,"AdExpandedChange",this),t.subscribe(this._adSkippableStateChangeHandler,"AdSkippableStateChange",this),t.subscribe(this._adDurationChangeHandler,"AdDurationChange",this),t.subscribe(this._adRemainingTimeChangeHandler,"AdRemainingTimeChange",this),t.subscribe(this._adVolumeChangeHandler,"AdVolumeChange",this),t.subscribe(this._adImpressionHandler,"AdImpression",this),t.subscribe(this._adClickThruHandler,"AdClickThru",this),t.subscribe(this._adInteractionHandler,"AdInteraction",this),t.subscribe(this._adVideoStartHandler,"AdVideoStart",this),t.subscribe(this._adVideoFirstQuartileHandler,"AdVideoFirstQuartile",this),t.subscribe(this._adVideoMidpointHandler,"AdVideoMidpoint",this),t.subscribe(this._adVideoThirdQuartileHandler,"AdVideoThirdQuartile",this),t.subscribe(this._adVideoCompleteHandler,"AdVideoComplete",this),t.subscribe(this._adUserAcceptInvitationHandler,"AdUserAcceptInvitation",this),t.subscribe(this._adUserMinimizeHandler,"AdUserMinimize",this),t.subscribe(this._adUserCloseHandler,"AdUserClose",this),t.subscribe(this._adPausedHandler,"AdPaused",this),t.subscribe(this._adPlayingHandler,"AdPlaying",this),t.subscribe(this._adErrorHandler,"AdError",this),t.subscribe(this._adLogHandler,"AdLog",this))},_adLoadedHandler:function(){n.log("ad has been loaded");n.sendMessageToAdSdk("AdLoaded")},_adPausedHandler:function(){n.log("ad paused");n.sendMessageToAdSdk("AdPaused")},_adPlayingHandler:function(){n.log("ad playing");n.sendMessageToAdSdk("AdPlaying")},_adErrorHandler:function(t){n.log("ad error: "+t);var i={message:t};n.sendMessageToAdSdk("AdError:"+JSON.stringify(i))},_adLogHandler:function(t){n.log("ad log: "+t);var i={message:t};n.sendMessageToAdSdk("AdLog:"+JSON.stringify(i))},_adUserAcceptInvitationHandler:function(){n.log("AdUserAcceptInvitation");n.sendMessageToAdSdk("AdUserAcceptInvitation")},_adUserMinimizeHandler:function(){n.log("AdUserMinimize");n.sendMessageToAdSdk("AdUserMinimize")},_adUserCloseHandler:function(){n.log("AdUserClose");n.sendMessageToAdSdk("AdUserClose")},_adSkippableStateChangeHandler:function(){n.log("ad Skippable State Changed to: "+this._creative.getAdSkippableState());n.sendMessageToAdSdk("AdSkippableStateChange")},_adExpandedChangeHandler:function(){n.log("ad Expanded Changed to: "+this._creative.getAdExpanded());n.sendMessageToAdSdk("AdExpanded")},_adSizeChangeHandler:function(){n.log("ad size changed to: w="+this._creative.getAdWidth()+" h="+this._creative.getAdHeight());var t={width:this._creative.getAdWidth(),height:this._creative.getAdHeight()};n.sendMessageToAdSdk("AdSizeChange:"+JSON.stringify(t))},_adDurationChangeHandler:function(){n.log("ad duration changed to: "+this._creative.getAdDuration());var t={duration:this._creative.getAdDuration()};n.sendMessageToAdSdk("AdDurationChange:"+JSON.stringify(t))},_adRemainingTimeChangeHandler:function(){var t={remainingTime:this._creative.getAdRemainingTime()};n.sendMessageToAdSdk("AdRemainingTimeChange:"+JSON.stringify(t))},_adImpressionHandler:function(){n.log("ad impression");n.sendMessageToAdSdk("AdImpression")},_adClickThruHandler:function(t,i,r){n.log("click-through");var u={url:t,id:i,playerHandles:r};n.sendMessageToAdSdk("AdClickThru:"+JSON.stringify(u))},_adInteractionHandler:function(){n.log("ad interaction");n.sendMessageToAdSdk("AdInteraction")},_adVideoStartHandler:function(){n.log("video started");n.sendMessageToAdSdk("AdVideoStart")},_adVideoFirstQuartileHandler:function(){n.log("video 25% completed");n.sendMessageToAdSdk("AdVideoFirstQuartile")},_adVideoMidpointHandler:function(){n.log("video 50% completed");n.sendMessageToAdSdk("AdVideoMidpoint")},_adVideoThirdQuartileHandler:function(){n.log("video 75% completed");n.sendMessageToAdSdk("AdVideoThirdQuartile")},_adVideoCompleteHandler:function(){n.log("video completed");n.sendMessageToAdSdk("AdVideoComplete")},_adLinearChangeHandler:function(){n.log("ad linear has changed: "+this._creative.getAdLinear());n.sendMessageToAdSdk("AdLinearChange")},_adStartedHandler:function(){n.log("ad started");n.sendMessageToAdSdk("AdStarted")},_adStoppedHandler:function(){n.log("ad stopped");n.sendMessageToAdSdk("AdStopped")},_adSkippedHandler:function(){n.log("ad skipped");n.sendMessageToAdSdk("AdSkipped")},_adVolumeChangeHandler:function(){n.log("ad volume changed to - "+this._creative.getAdVolume());n.sendMessageToAdSdk("AdVolumeChange")}};n.MSG_TYPE_ERROR="AdError";n.reportAdError=function(t){n.log("AD ERROR: "+t);var i={message:t};n.sendMessageToAdSdk(n.MSG_TYPE_ERROR+":"+JSON.stringify(i))};n.sendMessageToAdSdk=function(n){window.external.notify(n)};n.isVersionSupported=function(n){if(!n||typeof n!="string")return!1;var t=n.split(".").map(function(n){return parseInt(n,10)}),i=t.length>0?t[0]:NaN,u=t.length>1?t[1]:0;return isNaN(i)||isNaN(u)?!1:i>r?!1:i===r&&u>e?!1:!0};n.isValidVpaidCreative=function(n){return typeof n=="object"&&n!==null&&n.handshakeVersion&&typeof n.handshakeVersion=="function"&&n.initAd&&typeof n.initAd=="function"&&n.startAd&&typeof n.startAd=="function"&&n.stopAd&&typeof n.stopAd=="function"&&n.skipAd&&typeof n.skipAd=="function"&&n.resizeAd&&typeof n.resizeAd=="function"&&n.pauseAd&&typeof n.pauseAd=="function"&&n.resumeAd&&typeof n.resumeAd=="function"&&n.expandAd&&typeof n.expandAd=="function"&&n.collapseAd&&typeof n.collapseAd=="function"&&n.subscribe&&typeof n.subscribe=="function"&&n.unsubscribe&&typeof n.unsubscribe=="function"?!0:!1};n.log=function(){};window._msVpaidImpl=n;var t="viewableChange",i="viewableDataChange",u="ViewableChange",f="ViewableDataChange",h="SdkVersion";s.prototype={addEventListener:function(r,e){(r===i||r===t)&&r&&typeof e=="function"&&((this._listeners[r]===null||typeof this._listeners[r]=="undefined")&&(this._listeners[r]=[]),n.log("adding listener for "+r),this._listeners[r].push(e),r===t?n.sendMessageToAdSdk(u+":"+JSON.stringify({listener:"start"})):r===i&&n.sendMessageToAdSdk(f+":"+JSON.stringify({listener:"start"})))},removeEventListener:function(r,e){var s,o;if(n.log("removing listener for "+r),_adClient.listeners[r]!==null&&typeof _adClient.listeners[r]!="undefined"){if(e===undefined||e===null||e==="")_adClient.listeners[r].length=0;else for(s=_adClient.listeners[r],o=0;o<s.length;o++)if(s[o]===e){s.splice(o,1);break}(_adClient.listeners[r]===null||typeof _adClient.listeners[r]=="undefined"||_adClient.listeners[r].length===0)&&(r===t?(n.log("stopping viewable changed event: "+r+" (no more client listeners)"),n.sendMessageToAdSdk(u+":"+JSON.stringify({listener:"stop"}))):r===i&&(n.log("stopping viewable data changed event: "+r+" (no more client listeners)"),n.sendMessageToAdSdk(f+":"+JSON.stringify({listener:"stop"}))))}},getSize:function(){return typeof this._adSize=="undefined"&&(this._adSize={}),this._adSize},getSdkVersion:function(){return this._sdkInfo||(this._sdkInfo={}),this._sdkInfo},receiveMessageFromAdSdk:function(r){var l,v,e;if(r&&typeof r=="string"){var c=r,o=null,s=null;try{l=c.indexOf(":");l<0?o=c:(o=c.substr(0,l),s=c.substr(l+1));o===u?(v=s?s.toLowerCase()==="true":!1,this._fireEvent(t,v)):o===f?(e=JSON.parse(s),this._fireEvent(i,e)):o==="ResizeAd"?(e=JSON.parse(s),this._setSize(e.width,e.height)):o===h&&(e=JSON.parse(s),this._setSdkVersion(e.sdkVersion,e.client,e.runtimeType))}catch(a){n.log("Maple error handling message of type: "+o+": "+(a&&a.message?a.message:"unknown"));n.reportAdError("Maple error handling message of type "+o)}}},_setSize:function(t,i){n.log("setting Maple size to "+t+" x "+i);this._adSize={width:t,height:i}},_setSdkVersion:function(t,i,r){this._sdkInfo={sdkVersion:t,client:i,runtimeType:r,appName:navigator.appName,appVersion:navigator.appVersion,userAgent:navigator.userAgent,platform:navigator.platform};n.log("Ad SDK version: "+t+", "+i+", "+r)},_fireEvent:function(r,u){if(n.log("raising event "+r+" with data "+u),this._listeners[r]!==null&&typeof this._listeners[r]!="undefined")try{var e=this._listeners[r].slice(),f;switch(r){case t:case i:for(f=0;f<e.length;f++)e[f](u);break;default:return}}catch(o){n.log("exception thrown while firing event: "+o.message)}else n.log("no listeners for event "+r)}};window.Maple=window.maple=window.MAPLE=new s})();
// SIG // Begin signature block
// SIG // MIIdogYJKoZIhvcNAQcCoIIdkzCCHY8CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFGrSFUmvCBv9
// SIG // iRVy0Duc5RWNrPpToIIYZDCCBMMwggOroAMCAQICEzMA
// SIG // AACZqsWBn4yifYoAAAAAAJkwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE2MDMzMDE5
// SIG // MjEyOFoXDTE3MDYzMDE5MjEyOFowgbMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsT
// SIG // Hm5DaXBoZXIgRFNFIEVTTjo5OEZELUM2MUUtRTY0MTEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBAIqQrYfOhUbtcq7bD7tjS0le57+gP6FQHLxqxu1U
// SIG // MEZ/sBpV6wX+J8osmxxp/TMbgfbuBDLx/LO+XZLe91k+
// SIG // 5RiE9cgiIfVQvXbNYln5sR2bWLrVDjPdvmttrpEFtNE/
// SIG // FNsqMGehmr+EO/vTNVKz54mVw8DN1qptMJJJZsH4BBJv
// SIG // ssgmzJDURUghvTyM2apugrgb3Y4vZzL37k5asWlm2hYF
// SIG // UWoJYc/v3iyU9XuOQLBp4vV5Iyi+lSa2m8UQGMxDMOKk
// SIG // lrIaB7BIdjw9Yrioy72LKVr+BAQkDzyDqRmDsaTFkatL
// SIG // f4KgvqCZ14B8Og+X2dgnKpruP7t3Df2gLfvbsOMCAwEA
// SIG // AaOCAQkwggEFMB0GA1UdDgQWBBR21hL4ugVW8LHHssL5
// SIG // YyAraLcEETAfBgNVHSMEGDAWgBQjNPjZUkZwCu1A+3b7
// SIG // syuwwzWzDzBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
// SIG // Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
// SIG // cy9NaWNyb3NvZnRUaW1lU3RhbXBQQ0EuY3JsMFgGCCsG
// SIG // AQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL3d3
// SIG // dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3Nv
// SIG // ZnRUaW1lU3RhbXBQQ0EuY3J0MBMGA1UdJQQMMAoGCCsG
// SIG // AQUFBwMIMA0GCSqGSIb3DQEBBQUAA4IBAQAWzWDDLdyY
// SIG // 3zAJ7Y0IR6zs+GlJPe9H/4ScNYy32LKRaavhpFt4zJFL
// SIG // txnr/z40Za/6w7HhSDFxKtrRH/8qe9npenIJRQdf3G3w
// SIG // 3HYpi0A+lj2UMgH66RHHAi2qLn+5s/QxkNG/QvoWvd12
// SIG // aJ08D6lpqeXXPmIk6XgCnNb2qNPq7v37mUTnsfGXffa+
// SIG // nqGcdLVCMWgObE1jFumPtOb2TdzpPP/ocKjJcIDUfzZ1
// SIG // QDoNorJPcKMfUtaMmPWkc2tYyOOn25gvPM/eOBAny6/Y
// SIG // I2t1CkTJAdz9uOpbbIh9X89JBQKv5dnrq5n6BJ4YPJ9z
// SIG // h2OWv2c6NPlvbNcpX1HnKGeFMIIGBzCCA++gAwIBAgIK
// SIG // YRZoNAAAAAAAHDANBgkqhkiG9w0BAQUFADBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDcwNDAz
// SIG // MTI1MzA5WhcNMjEwNDAzMTMwMzA5WjB3MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
// SIG // DwAwggEKAoIBAQCfoWyx39tIkip8ay4Z4b3i48WZUSNQ
// SIG // rc7dGE4kD+7Rp9FMrXQwIBHrB9VUlRVJlBtCkq6YXDAm
// SIG // 2gBr6Hu97IkHD/cOBJjwicwfyzMkh53y9GccLPx754gd
// SIG // 6udOo6HBI1PKjfpFzwnQXq/QsEIEovmmbJNn1yjcRlOw
// SIG // htDlKEYuJ6yGT1VSDOQDLPtqkJAwbofzWTCd+n7Wl7Po
// SIG // IZd++NIT8wi3U21StEWQn0gASkdmEScpZqiX5NMGgUqi
// SIG // +YSnEUcUCYKfhO1VeP4Bmh1QCIUAEDBG7bfeI0a7xC1U
// SIG // n68eeEExd8yb3zuDk6FhArUdDbH895uyAc4iS1T/+QXD
// SIG // wiALAgMBAAGjggGrMIIBpzAPBgNVHRMBAf8EBTADAQH/
// SIG // MB0GA1UdDgQWBBQjNPjZUkZwCu1A+3b7syuwwzWzDzAL
// SIG // BgNVHQ8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwgZgG
// SIG // A1UdIwSBkDCBjYAUDqyCYEBWJ5flJRP8KuEKU5VZ5KSh
// SIG // Y6RhMF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJ
// SIG // kiaJk/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eYIQea0WoUqgpa1Mc1j0BxMuZTBQBgNVHR8ESTBHMEWg
// SIG // Q6BBhj9odHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtp
// SIG // L2NybC9wcm9kdWN0cy9taWNyb3NvZnRyb290Y2VydC5j
// SIG // cmwwVAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjho
// SIG // dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRz
// SIG // L01pY3Jvc29mdFJvb3RDZXJ0LmNydDATBgNVHSUEDDAK
// SIG // BggrBgEFBQcDCDANBgkqhkiG9w0BAQUFAAOCAgEAEJeK
// SIG // w1wDRDbd6bStd9vOeVFNAbEudHFbbQwTq86+e4+4LtQS
// SIG // ooxtYrhXAstOIBNQmd16QOJXu69YmhzhHQGGrLt48ovQ
// SIG // 7DsB7uK+jwoFyI1I4vBTFd1Pq5Lk541q1YDB5pTyBi+F
// SIG // A+mRKiQicPv2/OR4mS4N9wficLwYTp2OawpylbihOZxn
// SIG // LcVRDupiXD8WmIsgP+IHGjL5zDFKdjE9K3ILyOpwPf+F
// SIG // ChPfwgphjvDXuBfrTot/xTUrXqO/67x9C0J71FNyIe4w
// SIG // yrt4ZVxbARcKFA7S2hSY9Ty5ZlizLS/n+YWGzFFW6J1w
// SIG // lGysOUzU9nm/qhh6YinvopspNAZ3GmLJPR5tH4LwC8cs
// SIG // u89Ds+X57H2146SodDW4TsVxIxImdgs8UoxxWkZDFLyz
// SIG // s7BNZ8ifQv+AeSGAnhUwZuhCEl4ayJ4iIdBD6Svpu/RI
// SIG // zCzU2DKATCYqSCRfWupW76bemZ3KOm+9gSd0BhHudiG/
// SIG // m4LBJ1S2sWo9iaF2YbRuoROmv6pH8BJv/YoybLL+31HI
// SIG // jCPJZr2dHYcSZAI9La9Zj7jkIeW1sMpjtHhUBdRBLlCs
// SIG // lLCleKuzoJZ1GtmShxN1Ii8yqAhuoFuMJb+g74TKIdbr
// SIG // Hk/Jmu5J4PcBZW+JC33Iacjmbuqnl84xKf8OxVtc2E0b
// SIG // odj6L54/LlUWa8kTo/0wggYQMIID+KADAgECAhMzAAAA
// SIG // ZEeElIbbQRk4AAAAAABkMA0GCSqGSIb3DQEBCwUAMH4x
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
// SIG // c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwHhcNMTUx
// SIG // MDI4MjAzMTQ2WhcNMTcwMTI4MjAzMTQ2WjCBgzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjENMAsGA1UECxMETU9QUjEeMBwG
// SIG // A1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMIIBIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAky7a2OY+
// SIG // mNkbD2RfTahYTRQ793qE/DwRMTrvicJKLUGlSF3dEp7v
// SIG // q2YoNNV9KlV7TE2K8sDxstNSFYu2swi4i1AL3X/7agmg
// SIG // 3GcExPHfvHUYIEC+eCyZVt3u9S7dPkL5Wh8wrgEUirCC
// SIG // tVGg4m1l/vcYCo0wbU06p8XzNi3uXyygkgCxHEziy/f/
// SIG // JCV/14/A3ZduzrIXtsccRKckyn6B5uYxuRbZXT7RaO6+
// SIG // zUjQhiyu3A4hwcCKw+4bk1kT9sY7gHIYiFP7q78wPqB3
// SIG // vVKIv3rY6LCTraEbjNR+phBQEL7hyBxk+ocu+8RHZhbA
// SIG // hHs2r1+6hURsAg8t4LAOG6I+JQIDAQABo4IBfzCCAXsw
// SIG // HwYDVR0lBBgwFgYIKwYBBQUHAwMGCisGAQQBgjdMCAEw
// SIG // HQYDVR0OBBYEFFhWcQTwvbsz9YNozOeARvdXr9IiMFEG
// SIG // A1UdEQRKMEikRjBEMQ0wCwYDVQQLEwRNT1BSMTMwMQYD
// SIG // VQQFEyozMTY0Mis0OWU4YzNmMy0yMzU5LTQ3ZjYtYTNi
// SIG // ZS02YzhjNDc1MWM0YjYwHwYDVR0jBBgwFoAUSG5k5VAF
// SIG // 04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZD
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // cmwvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // bDBhBggrBgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
// SIG // dHMvTWljQ29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNy
// SIG // dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IC
// SIG // AQCI4gxkQx3dXK6MO4UktZ1A1r1mrFtXNdn06DrARZkQ
// SIG // Tdu0kOTLdlGBCfCzk0309RLkvUgnFKpvLddrg9TGp3n8
// SIG // 0yUbRsp2AogyrlBU+gP5ggHFi7NjGEpj5bH+FDsMw9Py
// SIG // gLg8JelgsvBVudw1SgUt625nY7w1vrwk+cDd58TvAyJQ
// SIG // FAW1zJ+0ySgB9lu2vwg0NKetOyL7dxe3KoRLaztUcqXo
// SIG // YW5CkI+Mv3m8HOeqlhyfFTYxPB5YXyQJPKQJYh8zC9b9
// SIG // 0JXLT7raM7mQ94ygDuFmlaiZ+QSUR3XVupdEngrmZgUB
// SIG // 5jX13M+Pl2Vv7PPFU3xlo3Uhj1wtupNC81epoxGhJ0tR
// SIG // uLdEajD/dCZ0xIniesRXCKSC4HCL3BMnSwVXtIoj/QFy
// SIG // mFYwD5+sAZuvRSgkKyD1rDA7MPcEI2i/Bh5OMAo9App4
// SIG // sR0Gp049oSkXNhvRi/au7QG6NJBTSBbNBGJG8Qp+5QTh
// SIG // KoQUk8mj0ugr4yWRsA9JTbmqVw7u9suB5OKYBMUN4hL/
// SIG // yI+aFVsE/KJInvnxSzXJ1YHka45ADYMKAMl+fLdIqm3n
// SIG // x6rIN0RkoDAbvTAAXGehUCsIod049A1T3IJyUJXt3OsT
// SIG // d3WabhIBXICYfxMg10naaWcyUePgW3+VwP0XLKu4O1+8
// SIG // ZeGyaDSi33GnzmmyYacX3BTqMDCCB3owggVioAMCAQIC
// SIG // CmEOkNIAAAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29m
// SIG // dCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEx
// SIG // MB4XDTExMDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVow
// SIG // fjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWlj
// SIG // cm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIw
// SIG // DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQ
// SIG // HC6t2G6qghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/D
// SIG // DB7dN2vGEtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRs
// SIG // r55JnOloXtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ2
// SIG // 6DJSJhIv56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea6
// SIG // 4DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3
// SIG // vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuG
// SIG // G9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGy
// SIG // r5I4ftKdgCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOG
// SIG // jfdf8NBSv4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKu
// SIG // HCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0Xpb
// SIG // L9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/p
// SIG // I0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkw
// SIG // p6uO3+xbn6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4Dm
// SIG // imJ4X7IvhNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJ
// SIG // TMXUpUMvdJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSW
// SIG // sLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEE
// SIG // AYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQw
// SIG // WgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEF
// SIG // BQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2Vy
// SIG // QXV0MjAxMV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGX
// SIG // MIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEW
// SIG // M2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
// SIG // ZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0
// SIG // HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMA
// SIG // dABhAHQAZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3S
// SIG // eQyQwWVfLiw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1
// SIG // pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4p
// SIG // m+Y9G6XUtR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJG
// SIG // KsKKELukqQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD
// SIG // 9MCP80Yr3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L
// SIG // 8giJ1h/DMhji8MUtzluetEk5CsYKwsatruWy2dsViFFF
// SIG // WDgycScaf7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEq
// SIG // KD6CPxNNZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobD
// SIG // HWM2l4bf2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbR
// SIG // BrF1HxS+YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADW
// SIG // oUa9WfOXpQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6
// SIG // IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9az
// SIG // I2h15q/6/IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5P
// SIG // v4BXIqF4ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJ
// SIG // m3ZbCoBIa/15n8G9bW1qyVJzEw16UM0xggSqMIIEpgIB
// SIG // ATCBlTB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQD
// SIG // Ex9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDEx
// SIG // AhMzAAAAZEeElIbbQRk4AAAAAABkMAkGBSsOAwIaBQCg
// SIG // gb4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
// SIG // KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZI
// SIG // hvcNAQkEMRYEFGb5dDCiBzbboyJDhHR3GSyYbhcrMF4G
// SIG // CisGAQQBgjcCAQwxUDBOoAyACgBBAGQAUwBEAEuhPoA8
// SIG // aHR0cDovL2Vkd2ViL3NpdGVzL0lTU0VuZ2luZWVyaW5n
// SIG // L0VuZ0Z1bi9TaXRlUGFnZXMvSG9tZS5hc3B4MA0GCSqG
// SIG // SIb3DQEBAQUABIIBAJDU8TEQM7UBamV428fKnMcMwUln
// SIG // CHI+hp1WI+Ubo4MKfX0hvhKQO32XHjB+FVwoNrTZmgRt
// SIG // MDAZWKWePmeYGfKPBrmAYjqLQifuSH93humvF+U47n15
// SIG // tGvGhIjkyWtB0lIwtAsA3xd1sCbeTGOK9xvgRgRYEhsR
// SIG // IZNRAj3fT8RFbrRm5yPGcgackXB/JnTd2hXgK9UILx5/
// SIG // s9S/+8d8WgZA8hNlq0jtkmnd6Wg3xACjv9yftHVnPrwf
// SIG // nn4qfDbJEpCCEwyL/GuG6HhiJ4fruuMyX+wH/QxDL5cB
// SIG // yJVU4Jo/WhIxHjXtp6nOLHgiqyyzQVDqjR2mNJY/iZul
// SIG // hheQoSShggIoMIICJAYJKoZIhvcNAQkGMYICFTCCAhEC
// SIG // AQEwgY4wdzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UE
// SIG // AxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBAhMzAAAA
// SIG // marFgZ+Mon2KAAAAAACZMAkGBSsOAwIaBQCgXTAYBgkq
// SIG // hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
// SIG // BTEPFw0xNjA5MjgxNjM4MDVaMCMGCSqGSIb3DQEJBDEW
// SIG // BBQ3Fw6Z1AIK2Sa+wqXPz9fv5d0lMjANBgkqhkiG9w0B
// SIG // AQUFAASCAQBZZupG1FhVDLE8nPNuMrvwbzEbU9RMNDLI
// SIG // WgYLc6cDoe9hPWN+mdRpYe06j3ASU0MAbF/5dJO3aAHX
// SIG // pn1OQ/O0A3r9ZJHJeV45pkoy3TFCA37p/NGc9Hrj6ZGe
// SIG // dB9XOnOKKxyyPCWRqqF3QaLBz00VyvR6vF6oS9b2EMix
// SIG // 8+v5MuaT6hOdzqiAhyRge7gdzBkmeUdoLaOQlE5N6zwF
// SIG // eOKBPjC+WKwUvCpUt8LBrGTY1RE0fnbbxkCUnQFQjIXI
// SIG // cFmQIUimjQ70qdxIatT7DcYEkIcZ4EJSSZLQkrfnUhxv
// SIG // 5/NKskFsw0Lw3fgzZGhXZgSE7tA8iRGx53f5PE2qyEus
// SIG // End signature block
